import{a as y,i,S as h}from"./assets/vendor-Qob_5Ba8.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const v="46912917-fb92bedb7f4b4973c6d37e29f",b="https://pixabay.com/api/";async function L(t,s,o){const a={key:v,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:o};return(await y.get(b,{params:a})).data}function w(t){return t.map(({webformatURL:s,largeImageURL:o,tags:a,likes:e=0,views:r=0,comments:n="",downloads:g=0})=>`
      <div class="images-gallery">
                <div class="loader" style="display: block;"></div> 
                <a href="${o}">
                    <img src="${s}" alt="${a}" />
                </a>
                <div class="content">
                    <div><p>Likes</p><span>${e}</span></div>
                    <div><p>Views</p><span>${r}</span></div>
                    <div><p>Comments</p><span>${n}</span></div>
                    <div><p>Downloads</p><span>${g}</span></div>
                </div>
            </div>
      `).join("")}function S(t){t.querySelectorAll(".images-gallery img").forEach(o=>{const a=o.closest(".images-gallery").querySelector(".loader");o.onload=()=>{a.style.display="none"},o.onerror=()=>{a.style.display="none"}})}const E=document.querySelector(".form"),u=document.querySelector(".gallery"),l=document.getElementById("load-more");let d=null,p="",c=1;const f=15;E.addEventListener("submit",$);l.addEventListener("click",q);async function $(t){if(t.preventDefault(),u.innerHTML="",c=1,p=t.target.elements.textName.value.trim(),p===""){i.warning({title:"Hey",message:"You forgot important data",color:"red"});return}await m()}async function m(){try{const t=await L(p,c,f);if(t.hits.length===0){i.warning({title:"Sorry",message:"No images found. Try a different search!",color:"orange"}),l.style.display="none";return}u.insertAdjacentHTML("beforeend",w(t.hits)),S(u),d?d.refresh():d=new h(".gallery .images-gallery a",{captionsData:"alt",captionDelay:250}),c*f>=t.totalHits?(i.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",color:"blue"}),l.style.display="none"):l.style.display="block",I()}catch(t){i.error({title:"Error",message:`Fetch error: ${t.message}`,color:"red"})}}function q(){c+=1,m()}function I(){const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
